archive:
  path: E:\bizdata\archive
csv:
  file:
    path: src/main/resources/data/BizKart_Export.csv
inbound:
  path: /usr/src/inbound
server:
  port: 8082
spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  application:
    name: bizdata-batch-processor
client:
  value: 6288BCEDBEDAFC2FC8E83B15A0EDC8EA
